---
# Stop existing Couch DB Docker containers and remove them (if any)
- name: Stop CouchDB Docker container
  become: yes
  docker_container:
    name: couchdb
    state: absent

# Create new docker container for CouchDB and start container
- name: Create and start CouchDB Docker container
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ CouchDBVERSION }}"
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    # volumes:
    #   - /data
    pull: yes
    env:
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
